/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkccM3ii0Fnp_fDlk-RsjROZuQFjvW4L4',
    appId: '1:538980718101:web:bd06c4fff49b9ea774601c',
    messagingSenderId: '538980718101',
    projectId: 'platzitripsflutter-a01f3',
    authDomain: 'platzitripsflutter-a01f3.firebaseapp.com',
    storageBucket: 'platzitripsflutter-a01f3.appspot.com',
    measurementId: 'G-VFYGRGF9XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcKxixCwIEgjtuRZMyhFvROYLQsm4UfI',
    appId: '1:538980718101:android:a0474790aded7b1574601c',
    messagingSenderId: '538980718101',
    projectId: 'platzitripsflutter-a01f3',
    storageBucket: 'platzitripsflutter-a01f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMgPNEXFUF312aMknODLcZMnJq6ktBlM',
    appId: '1:538980718101:ios:19af7b555517afa174601c',
    messagingSenderId: '538980718101',
    projectId: 'platzitripsflutter-a01f3',
    storageBucket: 'platzitripsflutter-a01f3.appspot.com',
    iosClientId: '538980718101-8rno0h3dpd54tnvesgfq4mcp261sjt50.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlatziTrips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMgPNEXFUF312aMknODLcZMnJq6ktBlM',
    appId: '1:538980718101:ios:19af7b555517afa174601c',
    messagingSenderId: '538980718101',
    projectId: 'platzitripsflutter-a01f3',
    storageBucket: 'platzitripsflutter-a01f3.appspot.com',
    iosClientId: '538980718101-8rno0h3dpd54tnvesgfq4mcp261sjt50.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlatziTrips',
  );
}
*/